// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Order struct {
	ID        uuid.UUID
	ProductID uuid.NullUUID
	Quantity  int32
	Status    string
	DelayRisk sql.NullFloat64
	CreatedAt sql.NullTime
}

type OrderStatusUpdate struct {
	ID        uuid.UUID
	OrderID   uuid.NullUUID
	Status    string
	CreatedAt sql.NullTime
}

type Product struct {
	ID        uuid.UUID
	Name      string
	Price     float64
	CreatedAt sql.NullTime
}
