// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	ProductID string `json:"productId"`
	Qty       int    `json:"qty"`
}

type Mutation struct {
}

type Order struct {
	ID             string   `json:"id"`
	Product        *Product `json:"product"`
	Qty            int      `json:"qty"`
	Status         string   `json:"status"`
	CreatedAt      string   `json:"createdAt"`
	DelayRiskScore float64  `json:"delayRiskScore"`
}

type Product struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}
